import { useState } from "react";
import { copyText } from "~/util";

// X:YからA:Bを求める - Generated by ChatGPT-4o
// ユークリッドの互除法
function gcd(a: number, b: number): number {
    return b === 0 ? a : gcd(b, a % b);
}
// 比率を求める
function getAspectRatio(x: number, y: number) {
    const divisor = gcd(x, y);
    const resultX = x / divisor;
    const resultY = y / divisor;
    return [resultX, resultY];
}

export default function RatioCalc() {
    const [inputX, setInputX] = useState(0);
    const [inputY, setInputY] = useState(0);
    const [inputCalc, setInputCalc] = useState(0);


    function Split({children}: {children: string}) {
        return <span className="mx-1 my-auto">{children}</span>
    }

    function formatInputNum(event: React.ChangeEvent<HTMLInputElement>) {
        const value = event.currentTarget.valueAsNumber;
        return Number.isNaN(value) ? 0 : value;
    }

    function CopyButton({value}: {value: any}) {
        return <button className="w-24" onClick={() => copyText(value)}>{String(value)}</button>
    }


    const result = inputCalc / inputX * inputY;
    const ratio = getAspectRatio(inputX, inputY);

    return (
        <>
            <div className="flex flex-row justify-center">
                <div className="my-auto">
                    <input type="number" value={inputX} onChange={e => setInputX(formatInputNum(e))} className="disable-spin-button w-24"/>
                    <Split>:</Split>
                    <input type="number" value={inputY} onChange={e => setInputY(formatInputNum(e))} className="disable-spin-button w-24"/>
                    <Split>=</Split>
                </div>
                <div className="flex flex-col">
                    <div className="flex flex-row">
                        <input type="number" value={inputCalc} onChange={e => setInputCalc(formatInputNum(e))} className="disable-spin-button w-24"/>
                        <Split>:</Split>
                        <CopyButton value={Math.floorEx(result, 2)}/>
                    </div>
                    <div className="flex flex-row">
                        <CopyButton value={ratio[0]}/>
                        <Split>:</Split>
                        <CopyButton value={ratio[1]}/>
                    </div>
                </div>
            </div>
        </>
    );
}
